[build]
  command = "npm install --legacy-peer-deps && npx next build --no-lint"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://joaillerie.netlify.app"
  NEXT_PUBLIC_DEBUG = "false"
  NEXT_PUBLIC_DEFAULT_THEME = "system"
  NEXT_PUBLIC_API_URL = "/api"

[dev]
  framework = "next"
  targetPort = 3000
  port = 3000
  target = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration des fonctions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]
  included_files = [".next/**"]

# Configuration spécifique pour la fonction de génération d'images
[functions.generate]
  node_bundler = "esbuild"
  timeout = 180  # 3 minutes

# Redirections pour l'API
[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
