[build]
  command = "npm install --legacy-peer-deps --include=dev && npm run build:prod"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "development"
  NEXT_PUBLIC_SITE_URL = "https://votre-nom-de-domaine.netlify.app"
  NEXT_PUBLIC_DEBUG = "false"
  NEXT_PUBLIC_DEFAULT_THEME = "system"
  NEXT_PUBLIC_API_URL = "/api"

[context.production]
  command = "npm install --legacy-peer-deps --include=dev && npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    NPM_FLAGS = "--legacy-peer-deps --include=dev"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps --include=dev && npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    NPM_FLAGS = "--legacy-peer-deps --include=dev"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps --include=dev && npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "production"
    NPM_FLAGS = "--legacy-peer-deps --include=dev"

[dev]
  framework = "next"
  targetPort = 3000
  port = 3000
  target = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"
