[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_VERSION = "9.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_SITE_URL = "https://votre-nom-de-domaine.netlify.app"
  NEXT_PUBLIC_DEBUG = "false"
  NEXT_PUBLIC_DEFAULT_THEME = "system"
  NEXT_PUBLIC_API_URL = "/api"

[dev]
  framework = "next"
  targetPort = 3000
  port = 3000
  target = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }
